name = "Platinum Pack"
author = "Fusion Flux"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3222ffb37be0be294b79f6b42dd5dfcd0399cfd1fcb1d1abde086b17394573a"

[versions]
forge = "1.20.1-47.3.11"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["fabric"]
