name = "Platinum Pack"
author = "Fusion Flux"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b30b0388f271b348800fb9fbfa9eea7d12accac826bad79c5ca0162576794d97"

[versions]
forge = "1.20.1-47.3.11"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["fabric"]
