name = "Platinum Pack"
author = "Fusion Flux"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "86138c6bc1dfce85cf19c720feb79762c364eee07ecab87c28dc5b40b70a6967"

[versions]
forge = "1.20.1-47.3.11"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["fabric"]
