name = "Platinum Pack"
author = "Fusion Flux"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0921c47c63af3ad49809d6827e4066d2359acb8f1a6fbdea5938914c225527e1"

[versions]
forge = "1.20.1-47.3.11"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["fabric"]
