name = "Platinum Pack"
author = "Fusion Flux"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d2d8b45cd8a50fec5d94cb30b5c94b798224cc8b8b6848b1b315b2c18a60988b"

[versions]
forge = "1.20.1-47.3.11"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["fabric"]
